language: python
services:
  - redis-server
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install tox flake8
  - (python --version 2>&1 | grep -q "Python 2.6" && pip install unittest2) || echo
before_script:
  - flake8 rache
  - flake8 tests.py
script:
  - python setup.py test
branches:
  only:
    - master
