language: python
python: 3.4
sudo: false
services:
  - redis-server
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=lint
install:
  - pip install tox
script:
  - tox -e $TOXENV
branches:
  only:
    - master
