language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - sudo apt-get update
  - sudo apt-get install redis-server
install:
  - pip install -r requirements-dev.txt
  - (python --version 2>&1 | grep -q "Python 2.6" && pip install unittest2) || echo
before_script:
  - flake8 rache
  - flake8 tests.py
script:
  - python setup.py test
branches:
  only:
    - master
